---
title: "Commercial Building Electrification at Scale"
 
output: 
  html_document:
    code_folding: hide

---



```{r Data Setup, echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}



my_packages <- c("tidyverse", "vroom" , "janitor" , "glue" ,  "tsibble" , "tidytext","lubridate", "fable", "tsibbledata", "ggplot2", "forecast", "tseries", "rio", "zoo", "readxl", "tsibbledata", "knitr", "kableExtra", "formattable") 
invisible( lapply(my_packages, require, character.only = TRUE))

#Choose one working site:
  place <- "Home"
# place <-  "work"


#Set proper working Dir 
if (place == "Home"){setwd("C:/Users/paulr/Documents/R/cbwg")} else
{setwd("C:/Users/prode/Documents/R/cbwg")}

# Check for data directory and if one is not present then make it
if (!file.exists("data")) {
  dir.create("data")}
  
# Set up the "not in" operator for later use. 
  `%!in%` <- Negate(`%in%`)
  
# Set number of Types to include in analysis. 
  "T" <- 100

rm(place, my_packages )

options(dplyr.summarise.inform = FALSE)

# Read in data 

LL97Text <- "https://www1.nyc.gov/assets/buildings/local_laws/ll97of2019.pdf"

L84_2015 <- read_excel("data/2015_nyc_benchmarking.xlsx", sheet = "2015 Data Reported in 2016", col_names = TRUE, na = "NA", col_types = NULL )%>% mutate(Sheet = "Information and Metrics") %>%    mutate(Data = "2015") 

L84_2015 %>%
  select( "Record Number", "Property Name", "NYC Borough, Block and Lot (BBL)", "Street Number","Street Name" , "Zip Code", "Borough", "Property GFA - Self-reported (ft²)", "Primary Property Type - Self Selected", "Year Built", "Number of Buildings - Self-reported", "Fuel Oil #1 Use (kBtu)", "Fuel Oil #2 Use (kBtu)", "Fuel Oil #4 Use (kBtu)", "Fuel Oil #5 & 6 Use (kBtu)", "Diesel #2 Use (kBtu)", "District Steam Use (kBtu)", "Natural Gas Use (kBtu)", "Electricity Use - Grid Purchase (kBtu)", "Water Use (All Water Sources) (kgal)","Total GHG Emissions (Metric Tons CO2e)", Data ) %>%
  data.frame() -> L84_2015

# Feature engineering to make consistent with base data frame. 
  L84_2015$Address <- paste(L84_2015$Street.Number, L84_2015$Street.Name, sep = ' ')
  L84_2015[-(4:5) ] -> L84_2015
  L84_2015 <- L84_2015 %>% relocate(Address, .after = NYC.Borough..Block.and.Lot..BBL.) 

  colnames(L84_2015) <- c( "id", "Name", "BBL", "Address", "Zip", "Boruugh", "GSF", "Type", "Built", "No.Buildings", "Oil1", "Oil2", "Oil4", "Oil56", "Diesel", "Steam", "N.Gas", "Elect", "Water", "GHG", "Data" )

 
L84_2015[c(7,9:21)] <- apply(L84_2015[c(7,9:21)], 2, as.numeric )
L84_2015[is.na(L84_2015)] <-0
L84_2015$Type <- as.factor(L84_2015$Type)
L84_2015 <- L84_2015 %>% mutate("T.Energy" = (Oil2 + Oil4 + Oil56 + Steam + N.Gas + Elect)) %>%
  mutate(EUI = T.Energy/GSF) %>%
  relocate(T.Energy, .after = Address) %>% 
  relocate(EUI, .after = T.Energy) %>% 
  mutate("Type" = fct_lump(Type, n=T, w = T.Energy))  %>% 
  arrange(id, T.Energy) 

# Remove duplicates 

L84_2015 %>% arrange(BBL, Address, T.Energy) %>%
  distinct() %>%
  filter( T.Energy != 0 ) %>% 
  filter(GSF > 25000) %>% 
  filter(EUI <500 ) %>% 
  filter(EUI > 5) %>%
  distinct(BBL, .keep_all = TRUE) %>%
  filter(BBL != 0) -> L84_2015


# Consolidate BBL's 
L84_2015$BBL <- gsub("-", "", L84_2015$BBL)
L84_2015$BBL <- gsub("/", "", L84_2015$BBL)
L84_2015$BBL <- gsub(",", ";", L84_2015$BBL)
strsplit(L84_2015$BBL, ';', fixed=T) -> L84_2015$BBL
L84_2015$BBL <- L84_2015$BBL %>% as.character(L84_2015$BBL) 

# add tags for small, med-sized and large properties. 

L84_2015 <- L84_2015 %>% 
  mutate("SizeBin" = cut(L84_2015$GSF, breaks = c(0, 25000, 50000, 500000,10000000), include.lowest = TRUE, labels = c("Small", "MidSized", "Large", "Large"), right = TRUE)) %>% 
  relocate(SizeBin, .after = GSF)

L84_2015$Built <- as.numeric(L84_2015$Built)
L84_2015 <- L84_2015 %>% 
  mutate("AgeBin" = cut(L84_2015$Built, breaks = c(0, 1917, 1942, 1970,1990, 2022), include.lowest = TRUE, labels = c("PreWar", "PreModern", "Modern", "PostModern", "Current"), right = TRUE)) %>% 
  relocate(AgeBin, .after = Built)

L84_2015[c(7,12,14)] <- apply(L84_2015[c(7,12,14)], 2, as.numeric )


L84_2016 <- read_excel("data/2016_nyc_benchmarking.xlsx", sheet = "Information and Metrics", col_names = TRUE, na = "NA", col_types = NULL) 

L84_2016 %>% 
  mutate(Data = "2016") %>%
  select(`Property Id`, `Property Name`, `BBL - 10 digits`, `Address 1 (self-reported)`, `Postal Code`, Borough, `DOF Gross Floor Area`, `Primary Property Type - Self Selected`, `Year Built`, `Number of Buildings - Self-reported`,`Fuel Oil #1 Use (kBtu)`, `Fuel Oil #2 Use (kBtu)`, `Fuel Oil #4 Use (kBtu)`, `Fuel Oil #5 & 6 Use (kBtu)`, `Diesel #2 Use (kBtu)`, `District Steam Use (kBtu)`, `Natural Gas Use (kBtu)`, `Electricity Use - Grid Purchase (kBtu)`, `Water Use (All Water Sources) (kgal)`,"Total GHG Emissions (Metric Tons CO2e)" , Data ) %>%
  data.frame() -> L84_2016


colnames(L84_2016) <- c("id", "Name", "BBL", "Address", "Zip", "Boruugh", "GSF", "Type", "Built", "No.Buildings", "Oil1", "Oil2", "Oil4", "Oil56", "Diesel", "Steam", "N.Gas", "Elect", "Water","GHG", "Data") 

L84_2016[c(7,11:21)] <- apply(L84_2016[c(7,11:21)], 2, as.numeric )
L84_2016$id <- as.numeric(L84_2016$id)
L84_2016[is.na(L84_2016)] <-0
L84_2016$Type <- as.factor(L84_2016$Type)
L84_2016 <- L84_2016 %>% mutate("T.Energy" = (Oil2 + Oil4 + Oil56 + Steam + N.Gas + Elect)) %>%
  mutate(EUI = T.Energy/GSF) %>%
  relocate(T.Energy, .after = Address) %>% 
  relocate(EUI, .after = T.Energy) %>% 
  mutate("Type" = fct_lump(Type, n=T, w = T.Energy))  %>% 
  arrange(id, T.Energy) 

# Remove duplicates 

L84_2016 %>% arrange(BBL, Address, T.Energy) %>%
  distinct() %>%
  filter( T.Energy != 0 ) %>% 
  filter(GSF > 25000) %>% 
  filter(EUI <500 ) %>% 
  filter(EUI > 5) %>%
  distinct(BBL, .keep_all = TRUE) %>%
  filter(BBL != 0) -> L84_2016

# Consolidate BBL's 
L84_2016$BBL <- gsub("-", "", L84_2016$BBL)
L84_2016$BBL <- gsub("/", "", L84_2016$BBL)
L84_2016$BBL <- gsub(",", ";", L84_2016$BBL)
strsplit(L84_2016$BBL, ';', fixed=T) -> L84_2016$BBL
L84_2016$BBL <- L84_2016$BBL %>% as.character(L84_2016$BBL) 


# add tags for small, med-sized and large properties. 

L84_2016 <- L84_2016 %>% 
  mutate("SizeBin" = cut(L84_2016$GSF, breaks = c(0, 25000, 50000, 500000,10000000), include.lowest = TRUE, labels = c("Small", "MidSized", "Large", "Large"), right = TRUE)) %>% 
  relocate(SizeBin, .after = GSF)

L84_2016$Built <- as.numeric(L84_2016$Built)
L84_2016 <- L84_2016 %>% 
  mutate("AgeBin" = cut(L84_2016$Built, breaks = c(0, 1917, 1942, 1970,1990, 2022), include.lowest = TRUE, labels = c("PreWar", "PreModern", "Modern", "PostModern", "Current"), right = TRUE)) %>% 
  relocate(AgeBin, .after = Built)

L84_2016[c(7,12,14)] <- apply(L84_2016[c(7,12,14)], 2, as.numeric )

L84_2017 <- read_csv("data/Energy_and_Water_Data_Disclosure_for_Local_Law_84_2018__Data_for_Calendar_Year_2017_.csv", col_names = TRUE, na = "NA" )

L84_2017 %>% mutate(Data = "2017") %>% 
  select( `Property Id`, `Property Name`, `NYC Borough, Block and Lot (BBL)`, `Address 1`, `Postcode`, `City`, `Property GFA - Self-Reported (ft²)`, `Primary Property Type - Self Selected`, `Year Built`, `Number of Buildings`,`Fuel Oil #1 Use (kBtu)`, `Fuel Oil #2 Use (kBtu)`, `Fuel Oil #4 Use (kBtu)`, `Fuel Oil #5 & 6 Use (kBtu)`, `Diesel #2 Use (kBtu)`, `District Steam Use (kBtu)`, `Natural Gas Use (kBtu)`, `Electricity Use - Grid Purchase (kBtu)`, `Water Use (All Water Sources) (kgal)`,"Total GHG Emissions (Metric Tons CO2e)", `Data` ) %>%
  data.frame() -> L84_2017

colnames(L84_2017) <- c("id",  "Name", "BBL", "Address", "Zip", "Boruugh", "GSF", "Type", "Built", "No.Buildings", "Oil1", "Oil2", "Oil4", "Oil56", "Diesel", "Steam", "N.Gas", "Elect", "Water", "GHG", "Data")

L84_2017[c(7,12:21)] <- apply(L84_2017[c(7,12:21)], 2, as.numeric )
L84_2017[is.na(L84_2017)] <-0
L84_2017$Type <- as.factor(L84_2017$Type)
L84_2017 <- L84_2017 %>% mutate("T.Energy" = (Oil2 + Oil4 + Oil56 + Steam + N.Gas + Elect)) %>%
  mutate(EUI = T.Energy/GSF) %>%
  relocate(T.Energy, .after = Address) %>% 
  relocate(EUI, .after = T.Energy) %>% 
  mutate("Type" = fct_lump(Type, n=T, w = T.Energy))  %>% 
  arrange(id, T.Energy) 

# Remove duplicates 
L84_2017 %>% arrange(BBL, Address, T.Energy) %>%
  distinct() %>%
  filter( T.Energy != 0 ) %>% 
  filter(GSF > 25000) %>% 
  filter(EUI <500 ) %>% 
  filter(EUI > 5) %>%
  distinct(BBL, .keep_all = TRUE) %>%
  filter(BBL != 0) -> L84_2017


# Consolidate BBL's 
L84_2017$BBL <- gsub("-", "", L84_2017$BBL)
L84_2017$BBL <- gsub("/", "", L84_2017$BBL)
L84_2017$BBL <- gsub(",", ";", L84_2017$BBL)
strsplit(L84_2017$BBL, ';', fixed=T) -> L84_2017$BBL
L84_2017$BBL <- L84_2017$BBL %>% as.character(L84_2017$BBL) 

# add tags for small, med-sized and large properties. 

L84_2017 <- L84_2017 %>% 
  mutate("SizeBin" = cut(L84_2017$GSF, breaks = c(0, 25000, 50000, 500000,10000000), include.lowest = TRUE, labels = c("Small", "MidSized", "Large", "Large"), right = TRUE)) %>% 
  relocate(SizeBin, .after = GSF)

L84_2017$Built <- as.numeric(L84_2017$Built)
L84_2017 <- L84_2017 %>% 
  mutate("AgeBin" = cut(L84_2017$Built, breaks = c(0, 1917, 1942, 1970,1990, 2022), include.lowest = TRUE, labels = c("PreWar", "PreModern", "Modern", "PostModern", "Current"), right = TRUE)) %>% 
  relocate(AgeBin, .after = Built)

L84_2017[c(7,12,14)] <- apply(L84_2017[c(7,12,14)], 2, as.numeric )

L84_2018 <- read_csv("data/Energy_and_Water_Data_Disclosure_for_Local_Law_84_2019__Data_for_Calendar_Year_2018_.csv", col_names = TRUE, na = "NA" )

L84_2018 %>% mutate(Data = "2018") %>% 
  select( `Property Id`, `Property Name`, `NYC Borough, Block and Lot (BBL)`, `Address 1`, `Postcode`, `City`, `Property GFA - Self-Reported (ft²)`, `Primary Property Type - Self Selected`, `Year Built`, `Number of Buildings`,`Fuel Oil #1 Use (kBtu)`, `Fuel Oil #2 Use (kBtu)`, `Fuel Oil #4 Use (kBtu)`, `Fuel Oil #5 & 6 Use (kBtu)`, `Diesel #2 Use (kBtu)`, `District Steam Use (kBtu)`, `Natural Gas Use (kBtu)`, `Electricity Use - Grid Purchase (kBtu)`, `Water Use (All Water Sources) (kgal)`, "Total GHG Emissions (Metric Tons CO2e)", `Data` ) %>%
  data.frame() -> L84_2018

colnames(L84_2018) <- c("id", "Name", "BBL", "Address", "Zip", "Boruugh", "GSF", "Type", "Built", "No.Buildings", "Oil1", "Oil2", "Oil4", "Oil56", "Diesel", "Steam", "N.Gas", "Elect", "Water", "GHG", "Data")


L84_2018[c(7,11:21)] <- apply(L84_2018[c(7,11:21)], 2, as.numeric )
L84_2018[is.na(L84_2018)] <-0
L84_2018$Type <- as.factor(L84_2018$Type)
L84_2018 <- L84_2018 %>% mutate("T.Energy" = (Oil2 + Oil4 + Oil56 + Steam + N.Gas + Elect)) %>%
  mutate(EUI = T.Energy/GSF) %>%
  relocate(T.Energy, .after = Address) %>% 
  relocate(EUI, .after = T.Energy) %>% 
  mutate("Type" = fct_lump(Type, n=T, w = T.Energy))  %>% 
  arrange(id, T.Energy) 


# Remove duplicates 
L84_2018 %>% arrange(BBL, Address, T.Energy) %>%
  distinct() %>%
  filter( T.Energy != 0 ) %>% 
  filter(GSF > 25000) %>% 
  filter(EUI <500 ) %>% 
  filter(EUI > 5) %>%
  distinct(BBL, .keep_all = TRUE) %>%
  filter(BBL != 0) -> L84_2018


# Consolidate BBL's 
L84_2018$BBL <- gsub("-", "", L84_2018$BBL)
L84_2018$BBL <- gsub("/", "", L84_2018$BBL)
L84_2018$BBL <- gsub(",", ";", L84_2018$BBL)
strsplit(L84_2018$BBL, ';', fixed=T) -> L84_2018$BBL
L84_2018$BBL <- L84_2018$BBL %>% as.character(L84_2018$BBL) 

# add tags for small, med-sized and large properties. 

L84_2018 <- L84_2018 %>% 
  mutate("SizeBin" = cut(L84_2018$GSF, breaks = c(0, 25000, 50000, 500000,10000000), include.lowest = TRUE, labels = c("Small", "MidSized", "Large", "Large"), right = TRUE)) %>% 
  relocate(SizeBin, .after = GSF)

L84_2018$Built <- as.numeric(L84_2018$Built)
L84_2018 <- L84_2018 %>% 
  mutate("AgeBin" = cut(L84_2018$Built, breaks = c(0, 1917, 1942, 1970,1990, 2022), include.lowest = TRUE, labels = c("PreWar", "PreModern", "Modern", "PostModern", "Current"), right = TRUE)) %>% 
  relocate(AgeBin, .after = Built)

L84_2018[c(7,12,14)] <- apply(L84_2018[c(7,12,14)], 2, as.numeric )


L84_2019 <- read_csv("data/Energy_and_Water_Data_Disclosure_for_Local_Law_84_2020__Data_for_Calendar_Year_2019_.csv", col_names = TRUE, na = "NA" )

L84_2019 %>% mutate(Data = "2019") %>% 
  select(`Property Id`, `Property Name`, `NYC Borough, Block and Lot (BBL)`, `Address 1`, `Postcode`, `City`, `Property GFA - Self-Reported (ft²)`, `Primary Property Type - Self Selected`, `Year Built`, `Number of Buildings`,`Fuel Oil #1 Use (kBtu)`, `Fuel Oil #2 Use (kBtu)`, `Fuel Oil #4 Use (kBtu)`, `Fuel Oil #5 & 6 Use (kBtu)`, `Diesel #2 Use (kBtu)`, `District Steam Use (kBtu)`, `Natural Gas Use (kBtu)`, `Electricity Use - Grid Purchase (kBtu)`, `Water Use (All Water Sources) (kgal)`, "Total GHG Emissions (Metric Tons CO2e)", `Data` ) %>%
  data.frame() -> L84_2019

colnames(L84_2019) <- c("id", "Name", "BBL", "Address", "Zip", "Boruugh", "GSF", "Type", "Built", "No.Buildings", "Oil1", "Oil2", "Oil4", "Oil56", "Diesel", "Steam", "N.Gas", "Elect", "Water", "GHG", "Data")

L84_2019[c(7,11:21)] <- apply(L84_2019[c(7,11:21)], 2, as.numeric )
L84_2019[is.na(L84_2019)] <-0
L84_2019$Type <- as.factor(L84_2019$Type)
L84_2019 <- L84_2019 %>% mutate("T.Energy" = (Oil2 + Oil4 + Oil56 + Steam + N.Gas + Elect)) %>%
  mutate(EUI = T.Energy/GSF) %>%
  relocate(T.Energy, .after = Address) %>% 
  relocate(EUI, .after = T.Energy) %>% 
  mutate("Type" = fct_lump(Type, n=T, w = T.Energy))  %>% 
  arrange(id, T.Energy) 


# Remove duplicates 
L84_2019 %>% arrange(BBL, Address, T.Energy) %>%
  distinct() %>%
  filter( T.Energy != 0 ) %>% 
  filter(GSF > 25000) %>% 
  filter(EUI <500 ) %>% 
  filter(EUI > 5) %>%
  distinct(BBL, .keep_all = TRUE) %>%
  filter(BBL != 0) -> L84_2019


# Consolidate BBL's 
L84_2019$BBL <- gsub("-", "", L84_2019$BBL)
L84_2019$BBL <- gsub("/", "", L84_2019$BBL)
L84_2019$BBL <- gsub(",", ";", L84_2019$BBL)
strsplit(L84_2019$BBL, ';', fixed=T) -> L84_2019$BBL
L84_2019$BBL <- L84_2019$BBL %>% as.character(L84_2019$BBL) 

# add tags for small, med-sized and large properties. 

L84_2019 <- L84_2019 %>% 
  mutate("SizeBin" = cut(L84_2019$GSF, breaks = c(0, 25000, 50000, 500000,10000000), include.lowest = TRUE, labels = c("Small", "MidSized", "Large", "Large"), right = TRUE)) %>% 
  relocate(SizeBin, .after = GSF)

L84_2019$Built <- as.numeric(L84_2019$Built)
L84_2019 <- L84_2019 %>% 
  mutate("AgeBin" = cut(L84_2019$Built, breaks = c(0, 1917, 1942, 1970,1990, 2022), include.lowest = TRUE, labels = c("PreWar", "PreModern", "Modern", "PostModern", "Current"), right = TRUE)) %>% 
  relocate(AgeBin, .after = Built)

L84_2019[c(7,12,14)] <- apply(L84_2019[c(7,12,14)], 2, as.numeric )


L84_2020 <- read_csv("data/Energy_and_Water_Data_Disclosure_for_Local_Law_84_2021__Data_for_Calendar_Year_2020_.csv", col_names = TRUE, na = "NA" )

L84_2020 %>% mutate(Data = "2020") %>% 
  select(`Property Id`, `Property Name`, `NYC Borough, Block and Lot (BBL)`, `Address 1`, `Postcode`, `City`, `Property GFA - Self-Reported (ft²)`, `Primary Property Type - Self Selected`, `Year Built`, `Number of Buildings`,`Fuel Oil #1 Use (kBtu)`, `Fuel Oil #2 Use (kBtu)`, `Fuel Oil #4 Use (kBtu)`, `Fuel Oil #5 & 6 Use (kBtu)`, `Diesel #2 Use (kBtu)`, `District Steam Use (kBtu)`, `Natural Gas Use (kBtu)`, `Electricity Use - Grid Purchase (kBtu)`, `Water Use (All Water Sources) (kgal)`, "Total GHG Emissions (Metric Tons CO2e)", `Data` ) %>%
  data.frame() -> L84_2020

colnames(L84_2020) <- c("id", "Name", "BBL", "Address", "Zip", "Boruugh", "GSF", "Type", "Built", "No.Buildings", "Oil1", "Oil2", "Oil4", "Oil56", "Diesel", "Steam", "N.Gas", "Elect", "Water", "GHG", "Data")

L84_2020[11:21] <- apply(L84_2020[11:21], 2, as.numeric )
L84_2020[is.na(L84_2020)] <-0
L84_2020$Type <- as.factor(L84_2020$Type)
L84_2020 <- L84_2020 %>% mutate("T.Energy" = (Oil2 + Oil4 + Oil56 + Steam + N.Gas + Elect)) %>%
  mutate(EUI = T.Energy/GSF) %>%
  relocate(T.Energy, .after = Address) %>% 
  relocate(EUI, .after = T.Energy) %>% 
  mutate("Type" = fct_lump(Type, n=T, w = T.Energy))  %>% 
  arrange(id, T.Energy) 

# Remove duplicates and outliers 

L84_2020 %>% arrange(BBL, Address, T.Energy) %>%
  distinct() %>%
  filter( T.Energy != 0 ) %>% 
  filter(GSF > 25000) %>% 
  filter(EUI <500 ) %>% 
  filter(EUI > 5) %>%
  distinct(BBL, .keep_all = TRUE) %>%
  filter(BBL != 0) -> L84_2020


# Consolidate BBL's 
L84_2020$BBL <- gsub("-", "", L84_2020$BBL)
L84_2020$BBL <- gsub("/", "", L84_2020$BBL)
L84_2020$BBL <- gsub(",", ";", L84_2020$BBL)
strsplit(L84_2020$BBL, ';', fixed=T) -> L84_2020$BBL
L84_2020$BBL <- L84_2020$BBL %>% as.character(L84_2020$BBL) 


# add tags for small, med-sized and large properties. 

L84_2020 <- L84_2020 %>% 
  mutate("SizeBin" = cut(L84_2020$GSF, breaks = c(0, 25000, 50000, 500000,10000000), include.lowest = TRUE, labels = c("Small", "MidSized", "Large", "Large"), right = TRUE)) %>% 
  relocate(SizeBin, .after = GSF)

L84_2020$Built <- as.numeric(L84_2020$Built)
L84_2020 <- L84_2020 %>% 
  mutate("AgeBin" = cut(L84_2020$Built, breaks = c(0, 1917, 1942, 1970,1990, 2022), include.lowest = TRUE, labels = c("PreWar", "PreModern", "Modern", "PostModern", "Current"), right = TRUE)) %>% 
  relocate(AgeBin, .after = Built)


AllData <- SameStore <- bind_rows(L84_2015, L84_2016, L84_2017, L84_2018, L84_2019, L84_2020)


#Create a vector containing unique same store properties by property id

L84_2020 %>% 
  inner_join(L84_2019, by = "BBL") %>% 
  inner_join(L84_2018, by = "BBL") %>% 
  inner_join(L84_2017, by = "BBL") %>% 
  inner_join(L84_2016, by = "BBL") %>%
  inner_join(L84_2015, by = "BBL") %>% 
  select(BBL) %>% 
  pull(BBL) -> AllYearsID


# create data frame of just samestore properties 

L84_2015 %>% 
  filter(BBL %in% AllYearsID) -> temp15
L84_2016 %>% 
  filter(BBL %in% AllYearsID) -> temp16
L84_2017 %>% 
  filter(BBL %in% AllYearsID) -> temp17
L84_2018 %>% 
  filter(BBL %in% AllYearsID) -> temp18
L84_2019 %>% 
  filter(BBL %in% AllYearsID) -> temp19
L84_2020 %>% 
  filter(BBL %in% AllYearsID) -> temp20

SameStore <- bind_rows(temp15, temp16, temp17,temp18, temp19, temp20) 
                      
remove(temp15, temp16, temp17, temp18, temp19, temp20)



# Add carbon parameters to the dataframes 

EmissionLimits <- read_excel("data/LL97Parameters .xlsx", sheet = "EmissionsLimits", col_names = TRUE, na = "NA",col_types = c("numeric", "text", "numeric", "text", "numeric") ) %>% drop_na()

CarbonFactors <- read_excel("data/LL97Parameters .xlsx", sheet = "CarbonFactors", col_names = TRUE, na = "NA",col_types = c("text", "numeric", "text", "numeric") ) %>% drop_na()


SameStore <- SameStore %>% 
  mutate("E_2024_tCO2e" = Elect * 	0.000288962/3.214) %>%
  mutate("E_2030_tCO2e" = Elect * 	0.000288962/3.214) %>%
  mutate("E_2035_tCO2e" = Elect * 	0.000288962/3.214) %>%
  mutate("G_2024_tCO2e" = N.Gas * 	0.000053110) %>%
  mutate("G_2030_tCO2e" = N.Gas * 	0.000053110) %>%
  mutate("G_2035_tCO2e" = N.Gas * 	0.000053110) %>%
  mutate("S_2024_tCO2e" = Steam * 	0.000044930) %>%
  mutate("S_2030_tCO2e" = Steam * 	0.000044930) %>%
  mutate("S_2035_tCO2e" = Steam * 	0.000044930) %>%
  mutate("O1_2024_tCO2e" = Oil1 * 	0.000074210) %>%
  mutate("O1_2030_tCO2e" = Oil1 * 	0.000074210) %>% 
  mutate("O1_2035_tCO2e" = Oil1 * 	0.000074210) %>% 
  mutate("O2_2024_tCO2e" = Oil2 * 	0.000074210) %>%
  mutate("O2_2030_tCO2e" = Oil2 * 	0.000074210) %>% 
  mutate("O2_2035_tCO2e" = Oil2 * 	0.000074210) %>%
  mutate("O4_2024_tCO2e" = Oil4 * 	0.000075290) %>%
  mutate("O4_2030_tCO2e" = Oil4 * 	0.000075290) %>%
  mutate("O4_2035_tCO2e" = Oil4 * 	0.000075290) %>% 
  mutate("O56_2024_tCO2e" = Oil56 * 	0.000075290) %>%
  mutate("O56_2030_tCO2e" = Oil56 * 	0.000075290) %>% 
  mutate("O56_2035_tCO2e" = Oil56 * 	0.000075290) %>%
  mutate("D_2024_tCO2e" = Diesel * 	0.000075290) %>%
  mutate("D_2030_tCO2e" = Diesel * 	0.000075290) %>%
  mutate("D_2035_tCO2e" = Diesel * 	0.000075290) %>%
  mutate("tCO2e_2024" = E_2024_tCO2e + G_2024_tCO2e + S_2024_tCO2e + O1_2024_tCO2e + O2_2024_tCO2e + O4_2024_tCO2e + O56_2024_tCO2e + D_2024_tCO2e) %>% 
    mutate("tCO2e_2030" = E_2030_tCO2e + G_2030_tCO2e + S_2030_tCO2e + O1_2030_tCO2e + O2_2030_tCO2e + O4_2030_tCO2e + O56_2030_tCO2e + D_2030_tCO2e) %>% 
      mutate("tCO2e_2035" = E_2035_tCO2e + G_2035_tCO2e + S_2035_tCO2e + O1_2035_tCO2e + O2_2035_tCO2e + O4_2035_tCO2e + O56_2035_tCO2e + D_2035_tCO2e) %>%
  mutate("Limit_2024" = 0.00846 * GSF) %>% 
  mutate("Limit_2030" = 0.00453 * GSF) %>%
  mutate("Limit_2035" = 0.00140 * GSF) %>% 
  mutate("penality_2024" = 268 * ( tCO2e_2024 - Limit_2024 )) %>% 
  mutate("penality_2030" = 268 * ( tCO2e_2030 - Limit_2030 )) %>%
  mutate("penality_2035" = 268 * ( tCO2e_2035 - Limit_2035 )) %>%
  relocate(tCO2e_2024, .after = T.Energy) %>% 
  relocate(penality_2024, .after = T.Energy) 


#Summarize Types of buildings 

Types <- SameStore %>%
  group_by(Type) %>%  
  summarise("Number" = sum(No.Buildings), "GSF" = sum(GSF), "T.Energy" = sum(T.Energy), "tCO2e_2024" = sum(tCO2e_2024))  %>% 
  mutate(GSF_1000xSF  = GSF/1000, T.Energy_MMbtu = T.Energy/1000) %>%
  arrange(desc(T.Energy_MMbtu)) 


#Calculate emissions limits per year for Office 

SameStore %>% 
  filter(Type == "Office") %>% 
  group_by(Data) %>% 
   summarise("Elect" = sum(Elect), "NGas" = sum(N.Gas), "Steam" = sum(Steam), GSF = sum(GSF)) %>% 
  mutate("EmmisionsLimit" = 0.00846 * GSF) -> Office_Emissions_Limits
OfficeEmmisions <- mean(Office_Emissions_Limits$EmmisionsLimit) 


# Tabulate total mid and large emissions attributed to buildings per UG report
CityEmissions_2019 <- 55100000

LL84Emissions_2019 <- sum(SameStore %>% filter(Data == 2019)%>% summarise(tCO2e_2024))

LL84Emissions_2019/CityEmissions_2019

```



```{r Tables, echo=FALSE, message=FALSE, warning=FALSE}

# 1 TABLE Number of Types in each submission year

data.frame("Description" = "Types", 'Yr 2015' = length(levels( L84_2015$Type )), 'Yr 2016'= length(levels(L84_2016$Type)), 'Yr 2017' = length(levels( L84_2017$Type )), 'Yr 2018'= length(levels(L84_2018$Type)),'Yr 2019' = length(levels( L84_2019$Type )), 'Yr 2020'= length(levels(L84_2020$Type))) %>% 
  kable( caption = "<center><strong><strong>Number of use types in each submission</strong></strong></center>") %>% 
  kable_styling() 




# 2 TABLE Number of Buildings in each Use Type by Submission

AllData %>% 
  group_by(Data, Type) %>% 
  summarise( "No.Buildings" = sum(No.Buildings)) %>% 
  spread(key = Data, value = No.Buildings) %>% 
  kable(digits = 3, 
        col.names = c("Building Use Type", "2015", "2016", "2017", "2018", "2019", "2020"),
        align = "lcccccc", 
        caption = "<center><strong><strong>Number of Buildings in each Use Type by Submission Year</strong></strong></center>",
        label = "Table 1", 
        format.args = list(decimal.mark = ".", big.mark = ","),
        escape = FALSE) %>% 
  kable_styling()



# 3 TABLE Number of Buildings in the top use Types by Submission

AllData %>% 
  mutate("Type" = fct_lump(Type, n=10, w = T.Energy)) %>% 
  group_by(Data, Type) %>% 
  summarise( "No.Buildings" = sum(No.Buildings)) %>% 
  spread(key = Data, value = No.Buildings) %>% 
  kable(digits = 3, 
        col.names = c("Building Use Type", "2015", "2016", "2017", "2018", "2019", "2020"),
        align = "lcccccc", 
        caption = "<center><strong><strong>Number of Buildings in the top use Types by Submission Year</strong></strong></center>",
        label = "Table 1", 
        format.args = list(decimal.mark = ".", big.mark = ","),
        escape = FALSE) %>% 
  kable_styling()

# 4 TABLE GSF of Buildings in each use Type by Submission Year

AllData %>% 
  mutate("Type" = fct_lump(Type, n=10, w = T.Energy)) %>% 
  group_by(Data, Type) %>% 
  summarise( "T.GSF" = sum(GSF)) %>% 
  spread(key = Data, value = T.GSF) %>% 
  kable(digits = 3, 
        col.names = c("Building Use Type", "2015", "2016", "2017", "2018", "2019", "2020"),
        align = "lcccccc", 
        caption = "<center><strong><strong>GSF of Buildings in each use Type by Submission Year</strong></strong></center>",
        label = "Table 1", 
        format.args = list(decimal.mark = ".", big.mark = ","),
        escape = FALSE) %>% 
  kable_styling()


# 5 TABLE Total Gross SF by submission year. 
AllData %>% 
  mutate("Type" = fct_lump(Type, n=10, w = T.Energy)) %>% 
  group_by(Data, Type) %>% 
  summarise( "T.GSF" = sum(GSF)) %>% 
  spread(key = Data, value = T.GSF) 


# Look at sf of submission by type by year

# 6 Look at sf of submission by type by year with EUI and %'s
L84_2019 %>% 
  select(Type, T.Energy, GSF) %>% 
  group_by(Type) %>% 
  summarise(EnergyS = sum(T.Energy), GSF = sum(GSF)) %>% 
  mutate("EnergyP" = EnergyS/sum(EnergyS)*100) %>% 
  mutate("GSF_P" = GSF/sum(GSF)*100) %>% 
  mutate("EUI" = EnergyS / GSF) %>% 
  mutate(across(where(is.numeric), ~ round(., digits = 3))) %>%
    arrange(desc(EnergyP))  %>% 
    select(Type, EnergyS, EnergyP, GSF_P, GSF, EUI) %>% 
  kable(format = "html", digits = 9, col.names = c("Use Type", "T.Energy", "% Energy", "% GSF", "GSF", "EUI")) %>%     kable_styling(full_width = FALSE)

# 7 

L84_2016 %>% 
  select(Type, T.Energy, GSF) %>% 
  group_by(Type) %>% 
  summarise(T.Energy = sum(T.Energy), GSF = sum(GSF)) %>% 
  mutate(across(where(is.numeric), ~ round(., digits = 3))) %>%
    arrange(desc(T.Energy))  %>% 
  kable(format = "html", digits = 9, col.names = c("Use Type", "T.Energy", "GSF")) %>%     
  kable_styling(full_width = FALSE)

# 8 

L84_2020 %>% 
  select(Type, GSF) %>% 
  group_by(Type) %>% 
  summarise(GSF = sum(GSF)) %>% 
  mutate(across(where(is.numeric), ~ round(., digits = 3))) %>%
    arrange(desc(GSF))  %>% 
  kable(format = "html", digits = 6, col.names = c("Use Type", "GSF")) %>%     
  kable_styling(full_width = FALSE)

# 9 Look carbon and EUI
L84_2019 %>% 
  select(Type, GHG, GSF) %>% 
  group_by(Type) %>% 
  summarise(GHG_S = sum(GHG), GSF = sum(GSF)) %>% 
  mutate("CUI" = GHG_S / GSF * 1000) %>% 
  mutate(across(where(is.numeric), ~ round(., digits = 3))) %>%
    arrange(desc(GSF))  %>% 
    select(Type, GSF, CUI) %>% 
  kable(format = "html", digits = 9, col.names = c("Use Type", "GSF", "CUI/1000")) %>%     
  kable_styling(full_width = FALSE)
```



Basic Charts


```{r EUIs, echo=FALSE, message=FALSE, warning=FALSE}
L84_2019 %>% 
  select(Type, T.Energy, Steam, N.Gas, Elect, GHG, GSF) %>% 
  group_by(Type) %>% 
  summarise(T.Energy = sum(T.Energy), Steam = sum(Steam), N.Gas = sum(N.Gas), Elect = sum(Elect), GHG = sum(GHG) ,GSF = sum(GSF)) %>% 
  mutate("EUI" = T.Energy / GSF) %>% 
  mutate(across(where(is.numeric), ~ round(., digits = 3))) %>%
    arrange(desc(T.Energy))  %>% 
    select(Type, T.Energy, Steam, N.Gas, Elect, GHG, GSF, EUI) -> EnergyAllocation
  

EnergyAllocation <- EnergyAllocation %>% 
  select(1, 3,4,5) %>% 
  gather(key = "Fuel", Value, 2:4, -Type, factor_key = TRUE)  

EnergyAllocation %>% 
  ggplot(aes(x = Type, y = Value, fill = Fuel)) +
  geom_col(position = "stack")+
  labs(title = "Energy Use by Building Type")
  ggsave( plot = last_plot(), device = "jpeg",
       path = "C:/Users/paulr/Documents/R/cbwg/", scale = 1 )

  EnergyAllocation %>% 
  ggplot(aes(x = Fuel, y = Value, )) +
  geom_col(position = "stack")+
  labs(title = "Energy Use by Fuel")
  ggsave( plot = last_plot(), device = "jpeg",
       path = "C:/Users/paulr/Documents/R/cbwg/", scale = 1 )



```


```{r EUIs, echo=FALSE, message=FALSE, warning=FALSE}

# Distribution of office energy use intensities using 2019
# & SizeBin == "Large"
# EUI Analysis 


L84_2020 %>% 
  filter(Type == "Office" & SizeBin == "Large") %>% 
  select(Name, EUI, SizeBin, AgeBin) -> OfficeEUI

p3 <- ggplot(OfficeEUI, aes(x=EUI)) +
  geom_density() +
  facet_wrap( ~ AgeBin )

s3 <- ggplot(OfficeEUI, aes(x=EUI, color = AgeBin)) +
  geom_density() 

w3 <- ggplot(OfficeEUI, aes(x=EUI, color = SizeBin)) +
  geom_density() 

p3
s3
w3

```






